version: "3.8"
services:
  api: 
    build: ./api
    container_name: api_c
    ports: 
      - '4000:4000'
    volumes:
      - ./api:/react_node_docker/api
      - /react_node_docker/api/node_modules
    depends_on:
      - mysql_server
  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=henri
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  frontend_react:
    build: ./app
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
