version: "3.8"
services:
  api: 
    build: ./api
    container_name: api_c
    ports: 
      - '4000:4000'
    volumes:
      - ./api:/react_node_docker/api
      - /react_node_docker/api/node_modules
  frontend_react:
    build: ./app
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
